CREATE DATABASE IF NOT EXISTS lab_db;
USE lab_db;

CREATE TABLE IF NOT EXISTS DEPT (
    DEPTNO INT PRIMARY KEY,
    DNAME VARCHAR(50),
    LOC VARCHAR(50)
);

INSERT INTO DEPT (DEPTNO, DNAME, LOC) VALUES
(10, 'ACCOUNTING', 'NEW YORK'),
(20, 'RESEARCH', 'DALLAS'),
(30, 'SALES', 'CHICAGO');

SELECT * FROM DEPT;

RENAME TABLE DEPT TO DEPARTMENT;
SELECT * FROM DEPARTMENT;

ALTER TABLE DEPARTMENT
ADD COLUMN PINCODE INT NOT NULL DEFAULT 0;
SELECT * FROM DEPARTMENT;

ALTER TABLE DEPARTMENT
CHANGE DNAME DEPT_NAME VARCHAR(50);
SELECT * FROM DEPARTMENT;

ALTER TABLE DEPARTMENT
MODIFY LOC CHAR(10);

DESCRIBE DEPARTMENT;

ALTER TABLE DEPARTMENT
DROP COLUMN LOC;
SELECT * FROM DEPARTMENT;

DROP TABLE DEPARTMENT;

SHOW TABLES;